// lib/shared/bootstrap.js — Bridge 自愈代码（共享模块）
// 由 cli.js 和 server/router.js 共用，确保一致的 __bridge 注入逻辑

const BRIDGE_BOOTSTRAP = `
(function(){
var BASE="https://www.zhipin.com";var _token=null;var _abc=null;
function h(m,f){var hd={'x-requested-with':'XMLHttpRequest'};if(m==='POST'&&f)hd['content-type']='application/x-www-form-urlencoded';if(_token)hd['token']=_token;return hd;}
function bq(p){if(!p)return'';var parts=[];for(var k in p){if(!p.hasOwnProperty(k))continue;var v=p[k];if(v===undefined||v===null)continue;parts.push(encodeURIComponent(k)+'='+encodeURIComponent(v));}return parts.length?'?'+parts.join('&'):'';}
function bf(p){if(!p)return undefined;var parts=[];for(var k in p){if(!p.hasOwnProperty(k))continue;var v=p[k];if(v===undefined||v===null)continue;parts.push(encodeURIComponent(k)+'='+encodeURIComponent(v));}return parts.length?parts.join('&'):undefined;}
async function call(m,path,p){var url=BASE+path+bq(m==='GET'?p:null);var body=m==='POST'?bf(p):undefined;var opts={method:m,credentials:'include',headers:h(m,body)};if(body)opts.body=body;var res=await fetch(url,opts);return await res.json();}
function findABC(){if(_abc)return true;try{for(var i=0;i<window.frames.length;i++){try{var fw=window.frames[i];if(fw&&fw.ABC&&typeof fw.ABC==='function'){_abc=fw.ABC;return true;}}catch(e){}}}catch(e){}return false;}
window.__bridge={getUserInfo:async function(){var d=await call('GET','/wapi/zpuser/wap/getUserInfo.json');if(d&&d.code===0&&d.zpData&&d.zpData.token)_token=d.zpData.token;return d;},search:function(p){p=Object.assign({page:1,pageSize:15,city:'100010000',query:'',expectInfo:'',multiSubway:'',multiBusinessDistrict:'',position:'',jobType:'',salary:'',experience:'',degree:'',industry:'',scale:'',stage:'',scene:1,encryptExpectId:''},p||{});return call('POST','/wapi/zpgeek/search/joblist.json',p);},jobDetail:function(sid,lid){return call('GET','/wapi/zpgeek/job/detail.json',{securityId:sid,lid:lid||''});},recommendJobs:function(p){p=Object.assign({page:1,pageSize:15,city:'100010000',encryptExpectId:''},p||{});return call('GET','/wapi/zpgeek/pc/recommend/job/list.json',p);},filterConditions:function(){return call('GET','/wapi/zpgeek/pc/all/filter/conditions.json');},citySite:function(){return call('GET','/wapi/zpgeek/common/data/city/site.json');},cityData:function(){return call('GET','/wapi/zpCommon/data/city.json');},friendList:function(eid){return call('POST','/wapi/zprelation/friend/getGeekFriendList.json',{});},friendListByLabel:function(lid,eid){return call('GET','/wapi/zprelation/friend/geekFilterByLabel',{labelId:lid||0,encryptSystemId:eid||''});},addFriend:function(sid,jid,lid){var url=BASE+'/wapi/zpgeek/friend/add.json'+bq({securityId:sid,jobId:jid,lid:lid||''});return fetch(url,{method:'POST',credentials:'include',headers:h('POST',false)}).then(function(r){return r.json();});},msgHistory:function(t,lid,sid){return call('GET','/wapi/zpmsg/history/pull',{type:t||0,lastId:lid||'',secretId:sid||''});},chatWsConfig:function(){return call('GET','/wapi/zpchat/config/ws');},chatConfig:function(){return call('GET','/wapi/zpchat/config/get');},industryData:function(){return call('GET','/wapi/zpCommon/data/industry.json');},resumeStep:function(){return call('GET','/wapi/zpgeek/resume/complete/step.json',{version:2});},expectList:function(){return call('GET','/wapi/zpgeek/pc/recommend/expect/list.json');},headerData:function(){return call('GET','/wapi/zpgeek/common/data/header.json');},resumeRestrictList:function(){return call('GET','/wapi/zpgeek/resume/restrict/list.json');},ensureToken:async function(){if(_token)return _token;var d=await call('GET','/wapi/zpuser/wap/getUserInfo.json');if(d&&d.code===0&&d.zpData)_token=d.zpData.token||null;return _token;},token:function(){return _token;},exposeAbc:function(){return findABC();},hasAbc:function(){return !!_abc;},genStoken:function(seed,ts){if(!findABC())throw new Error('ABC not found — security iframe may not be loaded');var correctedTs=parseInt(ts)+60*(480+new Date().getTimezoneOffset())*1000;var token=(new _abc()).z(seed,correctedTs);return{token:token,tokenEncoded:encodeURIComponent(token),tsUsed:correctedTs};},getPassportConfig:function(){try{var raw=localStorage.getItem('passport_config');return raw?JSON.parse(raw):null;}catch(e){return null;}}};
})()
`;

module.exports = { BRIDGE_BOOTSTRAP };
